#pragma once

#include <sstream>

#include "ir.h"
#include "utils.h"

namespace shikimori::ir {

static string ll_type(IRTypeRef t) {
    if (!t) return "void";
    
    auto visitor = overload {
        [](PrimTy p) -> string {
            switch (p) {
                case PrimTy::I8: case PrimTy::U8: return "i8";
                case PrimTy::I16: case PrimTy::U16: return "i16";
                case PrimTy::I32: case PrimTy::U32: return "i32";
                case PrimTy::I64: case PrimTy::U64: case PrimTy::USIZE: return "i64";
                case PrimTy::F32: return "float";
                case PrimTy::F64: return "double";
                case PrimTy::BOOL: return "i1";
                case PrimTy::STRING: return "{ i8*, i64 }";
            }
            return "i8";
        },
        [](const IRTyPointer& p) -> string { return ll_type(p.inner) + "*"; },
        [](const IRTySlice& s) -> string { return "{" + ll_type(s.inner) + "*, i64}"; },
        [](const IRTyArray& a) -> string { 
            return "[" + std::to_string(a.size) + " x " + ll_type(a.inner) + "]"; 
        },
        [](const IRTyNamed& n) -> string { return "%" + n.name; },
        [](const IRFnTy& f) -> string { return ll_type(f.return_type); },
        [](const IRTyInterfaceObj&) -> string { return "{ i8*, i8* }"; },
        [](const IRTyOptional& o) -> string { return "{" + ll_type(o.inner) + ", i1}"; },
        [](const IRTyInterface&) -> string { return "i8*"; }
    };
    return std::visit(visitor, t->ty);
}

struct LLVMMono {
    Module& mod;
    std::ostringstream out;
    
    LLVMMono(Module& m) : mod(m) {}
    
    string emit() {
        emit_preamble();
        emit_types();
        emit_globals();
        emit_functions();
        emit_externs();
        return out.str();
    }
    
private:
    void emit_preamble() {
        out << "; Generated by Shikimori\n";
        out << "target datalayout = \"e-m:e-p:64:64-i64:64-i128:128-n32:64-S128\"\n";
        out << "target triple = \"x86_64-pc-linux-gnu\"\n\n";
    }
    
    void emit_types() {
        for (auto& s : mod.structs) {
            out << "%" << s.name << " = type { ";
            for (size_t i = 0; i < s.fields.size(); i++) {
                if (i > 0) out << ", ";
                out << ll_type(s.fields[i].type);
            }
            out << " }\n";
        }
        out << "\n";
    }
    
    void emit_globals() {
        for (auto& g : mod.globals) {
            out << "@" << g.name << " = ";
            out << (g.is_constant ? "constant " : "global ");
            out << ll_type(g.type) << " ";
            if (g.init.kind == ConstKind::STRING) {
                out << "c\"" << esc(g.init.string_val) << "\\00\"";
            } else {
                out << "zeroinitializer";
            }
            out << "\n";
        }
        if (!mod.globals.empty()) out << "\n";
    }
    
    void emit_functions() {
        for (auto& fn : mod.functions) {
            emit_fn(fn);
        }
    }
    
    void emit_fn(const Function& fn) {
        out << "define " << ll_type(fn.return_type) << " @" << fn.name << "(";
        for (size_t i = 0; i < fn.params.size(); i++) {
            if (i > 0) out << ", ";
            out << ll_type(fn.params[i]->type) << " %p" << i;
        }
        out << ") {\n";
        
        for (auto& blk : fn.blocks) {
            out << "bb" << blk->id << ":\n";
            for (auto& phi : blk->phis) emit_inst(*phi);
            for (auto& inst : blk->instructions) emit_inst(*inst);
        }
        
        out << "}\n\n";
    }
    
    void emit_inst(const Instruction& inst) {
        auto emit_binop = [&](string name) {
            out << "  %" << inst.id << " = " << name << " " 
                << ll_type(inst.type) << " %" << inst.args[0]->id 
                << ", %" << inst.args[1]->id << "\n";
        };
        
        switch (inst.op) {
            case Opcode::ALLOCA:
                out << "  %" << inst.id << " = alloca " << ll_type(inst.type);
                if (inst.alloca_align) out << ", align " << inst.alloca_align;
                out << "\n";
                break;
            case Opcode::LOAD:
                out << "  %" << inst.id << " = load " << ll_type(inst.type) 
                    << ", " << ll_type(inst.args[0]->type) << " %" << inst.args[0]->id << "\n";
                break;
            case Opcode::STORE:
                out << "  store " << ll_type(inst.args[0]->type) << " %" << inst.args[0]->id
                    << ", " << ll_type(inst.args[1]->type) << " %" << inst.args[1]->id << "\n";
                break;
            case Opcode::RET:
                if (inst.args.empty()) out << "  ret void\n";
                else out << "  ret " << ll_type(inst.args[0]->type) << " %" << inst.args[0]->id << "\n";
                break;
            case Opcode::BR:
                out << "  br label %bb" << inst.default_dest->id << "\n";
                break;
            case Opcode::CBR:
                out << "  br i1 %" << inst.args[0]->id 
                    << ", label %bb" << inst.default_dest->id 
                    << ", label %bb" << inst.default_dest->id << "\n";
                break;
            case Opcode::PHI: {
                out << "  %" << inst.id << " = phi " << ll_type(inst.type) << " ";
                for (size_t i = 0; i < inst.phi_preds.size(); i++) {
                    if (i) out << ", ";
                    out << "%" << inst.phi_preds[i].first->id 
                        << ", %bb" << inst.phi_preds[i].second->id;
                }
                out << "\n";
                break;
            }
            case Opcode::CALL:
                out << "  %" << inst.id << " = call " << ll_type(inst.type) << " @" 
                    << inst.callee_name << "(";
                for (size_t i = 0; i < inst.args.size(); i++) {
                    if (i) out << ", ";
                    out << ll_type(inst.args[i]->type) << " %" << inst.args[i]->id;
                }
                out << ")\n";
                break;
            case Opcode::ADD: emit_binop("add"); break;
            case Opcode::SUB: emit_binop("sub"); break;
            case Opcode::MUL: emit_binop("mul"); break;
            case Opcode::SDIV: emit_binop("sdiv"); break;
            case Opcode::UDIV: emit_binop("udiv"); break;
            case Opcode::AND: emit_binop("and"); break;
            case Opcode::OR: emit_binop("or"); break;
            case Opcode::XOR: emit_binop("xor"); break;
            case Opcode::ICMP:
                out << "  %" << inst.id << " = icmp " << icmp_name(inst.cmp_kind) 
                    << " " << ll_type(inst.args[0]->type) << " %" << inst.args[0]->id 
                    << ", %" << inst.args[1]->id << "\n";
                break;
            case Opcode::SELECT:
                out << "  %" << inst.id << " = select i1 %" << inst.args[0]->id 
                    << ", " << ll_type(inst.args[1]->type) << " %" << inst.args[1]->id
                    << ", " << ll_type(inst.args[2]->type) << " %" << inst.args[2]->id << "\n";
                break;
            default:
                out << "  ; TODO: " << inst.op_name() << "\n";
        }
    }
    
    void emit_externs() {
        for (auto& e : mod.externs) {
            out << "declare " << ll_type(e.return_type) << " @" << e.name << "(";
            for (size_t i = 0; i < e.params.size(); i++) {
                if (i) out << ", ";
                out << ll_type(e.params[i]);
            }
            out << ")\n";
        }
    }
    
    string icmp_name(CompareKind k) {
        switch (k) {
            case CompareKind::EQ: return "eq";
            case CompareKind::NE: return "ne";
            case CompareKind::SLT: return "slt";
            case CompareKind::SLE: return "sle";
            case CompareKind::SGT: return "sgt";
            case CompareKind::SGE: return "sge";
            default: return "eq";
        }
    }
    
    string esc(const string& s) {
        string r;
        for (char c : s) {
            if (c == '\\') r += "\\\\";
            else if (c == '"') r += "\\22";
            else r += c;
        }
        return r;
    }
};

} // namespace shikimori::ir
